RecursionError: maximum recursion depth exceeded while calling a Python object
Get recursive error on write:
Because last changes on 29-Jul-2022 on write(), so can you please do the change according into def _get_stock_move_price_unit().

commit 87ffe5983be7f0f4a926b458c4bd1f13001048ec
Author: David Beal <david.beal@akretion.com>
Date:   Fri Jul 29 13:14:28 2022 +0000
    [FIX] purchase_stock: update price_unit in stock move
    closes odoo/odoo#96611
    Signed-off-by: William Henrotin (whe) <whe@odoo.com>